language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode

branches:
  only:
    - master
    - association-refactor

addons:
  code_climate:
    repo_token: ad6ebf3d8d1951c60aabbbb1211c8279ea7bcd2020fbb721577142a49afed6b1